---
language: java
jdk: openjdk11

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file:
    - 'build/distributions/*'
  skip_cleanup: true
  on:
    tags: true
