---
language: java
jdk: openjdk11

deploy:
  provider: releases
  api_key:
    secure: "OSL4nh4sBpou4TCMe2mGdbYn9WpG/niWAsn1MpY0a7TZAGO/OR+2DfMx4p1i8Fpl2uECcbaA3e7+iX/a599/Vo1oeR+Bvyx4QwI7gy6bMqHKa3HnK+NLJZxPQH/zFnQlRCR+ObmyzaN7Xy7spnqVOJBswBueozlk8hgShrlmwvy4qhePjD2HEndk9wtBGhROT+cmWdIxSM51qLPRCKJD+AhYWDBsfDkg55kkByjji/42B1fTRqERW38YmMAID5YP50mSKgyW97yAHN5Hdc23BoEnxjaIFJTNCxhUFt+AyUZHvXb+Mz5ilMjzlfGmnonTGWjtSmmSqbh9jzyVO/OHaH7y9dXrP75h6SR0hANiYCFk5ZOVOK3Y+KMbjuXMJ4zX4fhLj7TX8U6C/PRlkgmlGBXob/sJfSOVY7eaRPZ7mchZ4641yuiy2qHZNxd+ceIAiJ+FNLTynv/9FdpeAVdH5dXw4DzELcTKJUlYlhMBeZxixbAmcgEt6/Lb97G8P0lGg66sAvjW+DzOWKWvVp+zdLcLaydzb/jVVxKx8ovyZHMaevQcdx0Wu6NUCN4cneAZYAHVG9NtuC/VkMFgBZWwfA9or368Zk9dKN1B5FjlOFG2cqiTkJJTKJlY5Ijy7TvhNlY8Y6vq8PwRnxv3y+5g0p5WEPaqBPAzd74HMRuJPrg="
  file_glob: true
  file:
    - "build/distributions/*"
  skip_cleanup: true
  on:
    tags: true
